import { useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, Download, Beaker, Home } from "lucide-react";
import PaperChat from "@/components/PaperChat";

export default function PaperView() {
  const navigate = useNavigate();
  const location = useLocation();
  const state = location.state as any;
  const query = state?.query || "Scientific research question";
  const [paper, setPaper] = useState<any>(state?.paper);

  const title = paper?.title || "Research Paper";
  const abstract = paper?.abstract || "No abstract generated.";
  const introduction = paper?.introduction || "No introduction generated.";
  const methods = paper?.methods || "No methods generated.";
  const results = paper?.results || "No results generated.";
  const discussion = paper?.discussion || "No discussion generated.";
  const references = paper?.references || [];

  return (
    <div className="min-h-screen bg-background">
      <div className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <button
            onClick={() => navigate("/dashboard", { state: { query } })}
            className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors group"
          >
            <ArrowLeft className="h-4 w-4 group-hover:-translate-x-0.5 transition-transform" />
            Back to Dashboard
          </button>
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-[hsl(var(--aion-gradient-start))] to-[hsl(var(--aion-gradient-end))] flex items-center justify-center">
              <Beaker className="h-3 w-3 text-primary-foreground" />
            </div>
            <span className="text-sm font-bold text-foreground tracking-tight">AION</span>
          </div>
          <button className="aion-glow-button text-xs px-4 py-2 flex items-center gap-1.5 !rounded-xl !shadow-sm hover:!shadow-md">
            <Download className="h-3.5 w-3.5" />
            Download PDF
          </button>
        </div>
      </div>

      <motion.article
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-4xl mx-auto px-4 py-12"
      >
        <div className="glass-panel-elevated p-8 sm:p-12">
          <h1 className="font-serif text-2xl sm:text-3xl font-bold text-foreground leading-tight mb-2">
            {title}
          </h1>
          <p className="text-sm text-muted-foreground mb-1">Generated by AION — Autonomous AI Scientist</p>
          <p className="text-xs text-muted-foreground/60 mb-8">Research query: "{query}"</p>
          <hr className="border-border/40 mb-8" />

          <Section title="Abstract">{abstract}</Section>
          <Section title="1. Introduction">{introduction}</Section>
          <Section title="2. Methods">{methods}</Section>
          <Section title="3. Results">{results}</Section>
          <Section title="4. Discussion">{discussion}</Section>

          {references.length > 0 && (
            <Section title="References">
              <div className="space-y-2">
                {references.map((ref: any, i: number) => (
                  <p key={i} className="text-xs text-muted-foreground">{ref.text || ref}</p>
                ))}
              </div>
            </Section>
          )}
        </div>
      </motion.article>

      <PaperChat paper={paper} query={query} onPaperUpdate={setPaper} />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-serif text-lg font-bold text-foreground mb-3">{title}</h2>
      <div className="font-serif text-sm text-foreground/85 leading-relaxed whitespace-pre-line">{children}</div>
    </section>
  );
}
