import { useNavigate, useLocation } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, Download, Beaker } from "lucide-react";

export default function PaperView() {
  const navigate = useNavigate();
  const location = useLocation();
  const query = (location.state as any)?.query || "Microplastics and coral reef microbiomes";

  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <div className="sticky top-0 z-50 bg-background/80 backdrop-blur-lg border-b border-border">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <button onClick={() => navigate(-1)} className="flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors">
            <ArrowLeft className="h-4 w-4" />
            Back to Dashboard
          </button>
          <div className="flex items-center gap-2">
            <Beaker className="h-4 w-4 text-primary" />
            <span className="text-sm font-semibold text-foreground">AION</span>
          </div>
          <button className="aion-glow-button text-xs px-4 py-2 flex items-center gap-1.5">
            <Download className="h-3.5 w-3.5" />
            Download PDF
          </button>
        </div>
      </div>

      {/* Paper */}
      <motion.article
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-4xl mx-auto px-4 py-12"
      >
        <div className="glass-panel p-8 sm:p-12">
          {/* Title */}
          <h1 className="font-serif text-2xl sm:text-3xl font-bold text-foreground leading-tight mb-2">
            Biofilm-Mediated Toxin Transfer from Microplastic Surfaces to Coral Reef Tissue: A Computational Analysis
          </h1>
          <p className="text-sm text-muted-foreground mb-1">Generated by AION — Autonomous AI Scientist</p>
          <p className="text-xs text-muted-foreground mb-8">Research query: "{query}"</p>
          <hr className="border-border mb-8" />

          {/* Abstract */}
          <Section title="Abstract">
            <p>
              Microplastic pollution poses an emerging threat to coral reef ecosystems. This study investigates the hypothesis that microplastic surfaces serve as vectors for pathogenic biofilm formation, facilitating toxin transfer to coral tissue. Using Monte Carlo simulations parameterized by empirical data from recent studies, we demonstrate a statistically significant relationship between microplastic density and coral bleaching rates (p = 0.003, Cohen's d = 1.24). Our findings suggest that biofilm colonization on polymer surfaces creates a concentrated source of cytotoxic metabolites that compromise coral holobiont integrity.
            </p>
          </Section>

          {/* Introduction */}
          <Section title="1. Introduction">
            <p>
              Coral reefs, among Earth's most biodiverse ecosystems, face unprecedented anthropogenic pressures. While climate change and ocean acidification have received extensive attention, microplastic contamination represents an understudied yet potentially critical stressor (Harrison et al., 2023). Recent estimates suggest that reef environments contain 2.3–4.7 microplastic particles per liter of seawater, with concentrations rising annually (Zhang & Williams, 2024).
            </p>
            <p className="mt-3">
              The interaction between microplastics and coral-associated microbiomes remains poorly characterized. Prior work has established that polymer surfaces in marine environments rapidly acquire biofilm communities — the so-called "plastisphere" — which differ taxonomically from those on natural substrates (Zettler et al., 2022). However, the functional consequences of these novel biofilm assemblages for coral health have not been systematically evaluated.
            </p>
          </Section>

          {/* Methods */}
          <Section title="2. Methods">
            <p>
              We developed a stochastic simulation framework to model toxin transfer dynamics between microplastic-associated biofilms and coral tissue. The simulation incorporates:
            </p>
            <ul className="list-disc ml-6 mt-2 space-y-1">
              <li>Microplastic density gradients (0.1–10 particles/L)</li>
              <li>Biofilm colonization kinetics (logistic growth, K = 10⁸ CFU/cm²)</li>
              <li>Toxin production rates derived from <em>Vibrio coralliilyticus</em> cultures</li>
              <li>Coral tissue exposure models based on polyp filtration rates</li>
            </ul>
            <p className="mt-3">
              5,000 Monte Carlo iterations were performed for each density condition, with bleaching threshold defined as cumulative toxin exposure exceeding 50 μg·h/L. Statistical significance was assessed using Welch's t-test with Bonferroni correction.
            </p>
          </Section>

          {/* Results */}
          <Section title="3. Results">
            <p>
              Our simulations reveal a non-linear, dose-dependent relationship between microplastic density and predicted bleaching probability. At low densities (&lt;1 particle/L), bleaching risk remained at baseline levels (8.2 ± 2.1%). However, above a critical threshold of approximately 3.5 particles/L, bleaching probability increased sharply to 47.3 ± 6.8%, representing a 5.8-fold increase over baseline.
            </p>
            {/* Simulated figure placeholder */}
            <div className="my-6 bg-muted rounded-lg p-6 flex flex-col items-center">
              <div className="w-full max-w-md h-48 bg-gradient-to-r from-primary/10 via-primary/30 to-destructive/20 rounded-lg flex items-center justify-center text-muted-foreground text-sm">
                Figure 1: Microplastic Density vs. Bleaching Probability
              </div>
              <p className="text-xs text-muted-foreground mt-2 italic">
                Fig. 1. Non-linear relationship between microplastic density and coral bleaching probability (n=5000 simulations per condition).
              </p>
            </div>
            <p>
              The effect size (Cohen's d = 1.24) indicates a large practical significance, suggesting that microplastic-mediated toxin transfer could be a meaningful driver of reef degradation in contaminated environments.
            </p>
          </Section>

          {/* Discussion */}
          <Section title="4. Discussion">
            <p>
              These results support the biofilm-mediated toxin transfer hypothesis and identify a critical density threshold that may inform environmental policy. The non-linear response pattern is consistent with ecological tipping point theory and suggests that even moderate reductions in microplastic pollution could yield disproportionate benefits for reef health.
            </p>
            <p className="mt-3">
              Several limitations warrant consideration. Our model assumes uniform particle distribution, whereas real-world contamination is spatially heterogeneous. Additionally, the simulation does not account for coral acclimatization or immune responses, which may modulate toxin effects over chronic exposure periods. Future work should integrate empirical biofilm metabolomics data and validate predictions against field observations.
            </p>
          </Section>

          {/* References */}
          <Section title="References">
            <div className="text-xs space-y-2 text-muted-foreground">
              <p>Harrison, J.P., et al. (2023). "Microplastic contamination of coral reef environments: A systematic review." <em>Marine Pollution Bulletin</em>, 187, 114523.</p>
              <p>Zhang, L. & Williams, T.D. (2024). "Temporal trends in microplastic concentrations across Indo-Pacific reef systems." <em>Environmental Science & Technology</em>, 58(3), 1245–1254.</p>
              <p>Zettler, E.R., et al. (2022). "The plastisphere: Microbial communities on marine plastic debris." <em>Nature Reviews Microbiology</em>, 20, 159–173.</p>
              <p>Lamb, J.B., et al. (2018). "Plastic waste associated with disease on coral reefs." <em>Science</em>, 359(6374), 460–462.</p>
              <p>Sweet, M.J. & Bulling, M. (2017). "On the importance of the microbiome and pathobiome in coral health and disease." <em>Frontiers in Marine Science</em>, 4, 9.</p>
            </div>
          </Section>
        </div>
      </motion.article>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-serif text-lg font-bold text-foreground mb-3">{title}</h2>
      <div className="font-serif text-sm text-foreground/85 leading-relaxed">{children}</div>
    </section>
  );
}
