import { useState } from "react";
import { useNavigate, useLocation } from "react-router-dom";
import { motion } from "framer-motion";
import { ArrowLeft, Beaker, Home, Award } from "lucide-react";
import PaperChat from "@/components/PaperChat";
import PeerReview from "@/components/PeerReview";
import ReproducibilityExporter from "@/components/ReproducibilityExporter";

export default function PaperView() {
  const navigate = useNavigate();
  const location = useLocation();
  const state = location.state as any;
  const query = state?.query || "Scientific research question";
  const [paper, setPaper] = useState<any>(state?.paper);

  const title = paper?.title || "Research Paper";
  const abstract = paper?.abstract || "No abstract generated.";
  const introduction = paper?.introduction || "No introduction generated.";
  const methods = paper?.methods || "No methods generated.";
  const results = paper?.results || "No results generated.";
  const discussion = paper?.discussion || "No discussion generated.";
  const references = paper?.references || [];

  return (
    <div className="min-h-screen bg-background">
      <div className="sticky top-0 z-50 bg-background/80 backdrop-blur-xl border-b border-border">
        <div className="max-w-4xl mx-auto px-4 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <button
              onClick={() => navigate("/")}
              className="p-2 rounded-xl hover:bg-muted transition-colors text-muted-foreground hover:text-foreground"
              title="Home"
            >
              <Home className="h-4 w-4" />
            </button>
            <button
              onClick={() => navigate("/dashboard", { state: { query } })}
              className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors group"
            >
              <ArrowLeft className="h-3.5 w-3.5 group-hover:-translate-x-0.5 transition-transform" />
              Dashboard
            </button>
          </div>
          <div className="flex items-center gap-2">
            <div className="w-6 h-6 rounded-md bg-gradient-to-br from-[hsl(var(--aion-gradient-start))] to-[hsl(var(--aion-gradient-end))] flex items-center justify-center">
              <Beaker className="h-3 w-3 text-primary-foreground" />
            </div>
            <span className="text-sm font-bold text-foreground tracking-tight">AION</span>
          </div>
          <div className="flex items-center gap-2">
            <PeerReview paper={paper} query={query} onPaperUpdate={setPaper} />
            <ReproducibilityExporter paper={paper} query={query} />
          </div>
        </div>
      </div>

      <motion.article
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6 }}
        className="max-w-4xl mx-auto px-4 py-12"
      >
        <div className="glass-panel-elevated p-8 sm:p-12">
          {/* Badges */}
          <div className="flex items-center gap-2 mb-4">
            <span className="inline-flex items-center gap-1 text-[10px] font-semibold px-2.5 py-1 rounded-full bg-primary/10 text-primary">
              <Award className="h-3 w-3" />
              Reproducible
            </span>
            <span className="inline-flex text-[10px] font-semibold px-2.5 py-1 rounded-full bg-emerald-500/10 text-emerald-600">
              AI-Generated
            </span>
          </div>

          <h1 className="font-serif text-2xl sm:text-3xl font-bold text-foreground leading-tight mb-2">
            {title}
          </h1>
          <p className="text-sm text-muted-foreground mb-1">Generated by AION — Autonomous AI Scientist</p>
          <p className="text-xs text-muted-foreground/60 mb-8">Research query: "{query}"</p>
          <hr className="border-border/40 mb-8" />

          <Section title="Abstract">{abstract}</Section>
          <Section title="1. Introduction">{introduction}</Section>
          <Section title="2. Methods">{methods}</Section>
          <Section title="3. Results">{results}</Section>
          <Section title="4. Discussion">{discussion}</Section>

          {/* Limitations auto-generated */}
          <Section title="5. Limitations">
            <div className="space-y-2 text-xs text-foreground/80 leading-relaxed">
              <p>This study was conducted using AI-generated simulated data and should be considered exploratory. The following limitations apply:</p>
              <ul className="list-disc list-inside space-y-1 pl-2">
                <li>Data was synthetically generated and may not reflect real-world distributions.</li>
                <li>Statistical results are illustrative and require validation with empirical datasets.</li>
                <li>The literature review was AI-assisted and may not capture all relevant publications.</li>
                <li>Competing hypotheses were tested against the same simulated dataset.</li>
              </ul>
            </div>
          </Section>

          {references.length > 0 && (
            <Section title="References">
              <div className="space-y-2">
                {references.map((ref: any, i: number) => (
                  <p key={i} className="text-xs text-muted-foreground">{ref.text || ref}</p>
                ))}
              </div>
            </Section>
          )}
        </div>
      </motion.article>

      <PaperChat paper={paper} query={query} onPaperUpdate={setPaper} />
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-8">
      <h2 className="font-serif text-lg font-bold text-foreground mb-3">{title}</h2>
      <div className="font-serif text-sm text-foreground/85 leading-relaxed whitespace-pre-line">{children}</div>
    </section>
  );
}
