import { useState } from "react";
import { FileDown, Loader2, CheckCircle2 } from "lucide-react";

interface Props {
  paper: any;
  query: string;
}

export default function PaperPDFExporter({ paper, query }: Props) {
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(false);

  const exportPDF = async () => {
    if (!paper) return;
    setExporting(true);

    try {
      const { default: jsPDF } = await import("jspdf");

      const doc = new jsPDF({ unit: "mm", format: "a4" });
      const pageW = doc.internal.pageSize.getWidth();
      const pageH = doc.internal.pageSize.getHeight();
      const marginL = 25;
      const marginR = 25;
      const marginTop = 30;
      const marginBot = 25;
      const contentW = pageW - marginL - marginR;
      let y = marginTop;

      const checkPage = (needed: number) => {
        if (y + needed > pageH - marginBot) {
          doc.addPage();
          y = marginTop;
          addFooter();
        }
      };

      const addFooter = () => {
        const pageNum = doc.getNumberOfPages();
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(160, 160, 160);
        doc.text(`AION Research Platform — Page ${pageNum}`, pageW / 2, pageH - 12, { align: "center" });
        doc.setDrawColor(220, 220, 220);
        doc.line(marginL, pageH - 18, pageW - marginR, pageH - 18);
      };

      const writeText = (text: string, fontSize: number, opts?: { bold?: boolean; italic?: boolean; color?: [number, number, number]; lineHeight?: number; indent?: number }) => {
        const style = opts?.bold && opts?.italic ? "bolditalic" : opts?.bold ? "bold" : opts?.italic ? "italic" : "normal";
        doc.setFont("helvetica", style);
        doc.setFontSize(fontSize);
        doc.setTextColor(...(opts?.color || [40, 40, 40]));
        const lh = opts?.lineHeight || fontSize * 0.45;
        const indent = opts?.indent || 0;
        const lines = doc.splitTextToSize(text, contentW - indent);
        for (const line of lines) {
          checkPage(lh);
          doc.text(line, marginL + indent, y);
          y += lh;
        }
      };

      const writeSection = (title: string, content: string) => {
        checkPage(20);
        y += 6;
        // Section title
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(30, 30, 30);
        doc.text(title, marginL, y);
        y += 3;
        // Underline
        doc.setDrawColor(100, 120, 220);
        doc.setLineWidth(0.5);
        doc.line(marginL, y, marginL + doc.getTextWidth(title), y);
        y += 6;

        // Content paragraphs
        const paragraphs = content.split(/\n\n+/).filter(p => p.trim());
        paragraphs.forEach((para, i) => {
          writeText(para.trim(), 10, { lineHeight: 4.5, indent: i === 0 ? 0 : 0 });
          y += 3;
        });
      };

      // === TITLE PAGE ===
      y = 60;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(20);
      doc.setTextColor(30, 30, 30);
      const titleLines = doc.splitTextToSize(paper.title || "Research Paper", contentW);
      for (const line of titleLines) {
        doc.text(line, pageW / 2, y, { align: "center" });
        y += 9;
      }

      y += 8;
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(100, 100, 100);
      doc.text("Generated by AION — Autonomous AI Scientist", pageW / 2, y, { align: "center" });
      y += 6;
      doc.setFontSize(9);
      doc.text(`Research Query: "${query}"`, pageW / 2, y, { align: "center" });
      y += 6;
      doc.text(new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" }), pageW / 2, y, { align: "center" });

      // Decorative line
      y += 12;
      doc.setDrawColor(100, 120, 220);
      doc.setLineWidth(0.8);
      doc.line(pageW / 2 - 30, y, pageW / 2 + 30, y);

      // Badges
      y += 10;
      doc.setFontSize(8);
      doc.setTextColor(100, 120, 220);
      doc.text("✦ AI-Generated  ·  Reproducible  ·  Peer-Review Ready", pageW / 2, y, { align: "center" });

      addFooter();

      // === ABSTRACT ===
      doc.addPage();
      y = marginTop;
      addFooter();

      if (paper.abstract) {
        writeSection("Abstract", paper.abstract);
      }

      // === INTRODUCTION ===
      if (paper.introduction) {
        writeSection("1. Introduction", paper.introduction);
      }

      // === LITERATURE REVIEW ===
      const litReview = paper.literatureReview || paper.literature_review;
      let secNum = 2;
      if (litReview) {
        writeSection(`${secNum}. Literature Review`, litReview);
        secNum++;
      }

      // === METHODS ===
      if (paper.methods) {
        writeSection(`${secNum}. Methods`, paper.methods);
        secNum++;
      }

      // === RESULTS ===
      if (paper.results) {
        writeSection(`${secNum}. Results`, paper.results);
        secNum++;
      }

      // === DISCUSSION ===
      if (paper.discussion) {
        writeSection(`${secNum}. Discussion`, paper.discussion);
        secNum++;
      }

      // === CONCLUSION ===
      if (paper.conclusion) {
        writeSection(`${secNum}. Conclusion`, paper.conclusion);
        secNum++;
      }

      // === LIMITATIONS ===
      checkPage(30);
      y += 6;
      doc.setFont("helvetica", "bold");
      doc.setFontSize(13);
      doc.setTextColor(30, 30, 30);
      doc.text(`${secNum}. Limitations`, marginL, y);
      y += 3;
      doc.setDrawColor(100, 120, 220);
      doc.setLineWidth(0.5);
      doc.line(marginL, y, marginL + doc.getTextWidth(`${secNum}. Limitations`), y);
      y += 6;

      const limitations = [
        "Data was synthetically generated and may not reflect real-world distributions or population characteristics.",
        "Statistical results are illustrative and require validation with empirical datasets from controlled studies.",
        "The literature review was AI-assisted and may not capture all relevant publications, particularly recent preprints.",
        "Competing hypotheses were tested against the same simulated dataset, which may introduce correlated errors.",
        "Effect sizes and p-values should be interpreted with caution given the simulated nature of the data.",
        "External validity cannot be established without replication using real-world observational or experimental data.",
      ];

      writeText("This study was conducted using AI-generated simulated data and should be considered exploratory. The following limitations apply:", 10, { lineHeight: 4.5 });
      y += 2;
      limitations.forEach((lim) => {
        checkPage(10);
        writeText(`• ${lim}`, 9.5, { lineHeight: 4.2, indent: 4 });
        y += 1.5;
      });

      // === REFERENCES ===
      const refs = paper.references || [];
      if (refs.length > 0) {
        checkPage(20);
        y += 8;
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(30, 30, 30);
        doc.text("References", marginL, y);
        y += 3;
        doc.setDrawColor(100, 120, 220);
        doc.setLineWidth(0.5);
        doc.line(marginL, y, marginL + doc.getTextWidth("References"), y);
        y += 6;

        refs.forEach((ref: any, i: number) => {
          const refText = ref.text || ref;
          checkPage(12);
          doc.setFont("helvetica", "normal");
          doc.setFontSize(9);
          doc.setTextColor(80, 80, 80);
          const refLines = doc.splitTextToSize(`[${i + 1}] ${refText}`, contentW - 5);
          for (const line of refLines) {
            checkPage(4);
            doc.text(line, marginL + 2, y);
            y += 3.8;
          }
          y += 1.5;
        });
      }

      // Add footers to all pages
      const totalPages = doc.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(160, 160, 160);
        doc.text(`AION Research Platform — Page ${i} of ${totalPages}`, pageW / 2, pageH - 12, { align: "center" });
        doc.setDrawColor(220, 220, 220);
        doc.setLineWidth(0.3);
        doc.line(marginL, pageH - 18, pageW - marginR, pageH - 18);
      }

      // Save
      const safeTitle = (paper.title || "research-paper").replace(/[^a-zA-Z0-9]/g, "_").substring(0, 50);
      doc.save(`AION_${safeTitle}.pdf`);

      setExported(true);
      setTimeout(() => setExported(false), 4000);
    } catch (e) {
      console.error("PDF export error:", e);
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={exportPDF}
      disabled={exporting || !paper}
      className="aion-glow-button text-xs px-4 py-2 flex items-center gap-1.5 !rounded-xl !shadow-sm hover:!shadow-md disabled:opacity-50"
      title="Download as PDF"
    >
      {exporting ? (
        <Loader2 className="h-3.5 w-3.5 animate-spin" />
      ) : exported ? (
        <CheckCircle2 className="h-3.5 w-3.5" />
      ) : (
        <FileDown className="h-3.5 w-3.5" />
      )}
      {exporting ? "Generating…" : exported ? "Downloaded!" : "PDF"}
    </button>
  );
}
