import { useState } from "react";
import { Archive, CheckCircle2, Loader2 } from "lucide-react";

interface Props {
  paper: any;
  query: string;
}

export default function ReproducibilityExporter({ paper, query }: Props) {
  const [exporting, setExporting] = useState(false);
  const [exported, setExported] = useState(false);

  const exportPackage = async () => {
    if (!paper) return;
    setExporting(true);

    try {
      // Dynamically import JSZip
      const JSZip = (await import("jszip")).default;
      const zip = new JSZip();

      const seed = Math.floor(Math.random() * 999999);

      // README
      zip.file("README.md", `# ${paper.title || "AION Research"}\n\nGenerated by AION — Autonomous AI Scientist\n\n## Research Question\n${query}\n\n## Setup\n\`\`\`bash\npip install -r requirements.txt\npython main.py\n\`\`\`\n\n## Random Seed\n${seed}\n\n## Abstract\n${paper.abstract || "N/A"}\n`);

      // Requirements
      zip.file("requirements.txt", "numpy==1.26.4\npandas==2.2.1\nscipy==1.12.0\nmatplotlib==3.8.3\nseaborn==0.13.2\nscikit-learn==1.4.1\nstatsmodels==0.14.1\n");

      // Environment.yml
      zip.file("environment.yml", `name: aion-research\nchannels:\n  - defaults\n  - conda-forge\ndependencies:\n  - python=3.11\n  - numpy=1.26.4\n  - pandas=2.2.1\n  - scipy=1.12.0\n  - matplotlib=3.8.3\n  - seaborn=0.13.2\n  - scikit-learn=1.4.1\n`);

      // Main script
      zip.file("main.py", `#!/usr/bin/env python3
"""${paper.title || "AION Research"}
Generated by AION — Autonomous AI Scientist
Research Question: ${query}
"""
import numpy as np
import pandas as pd
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns

RANDOM_SEED = ${seed}
np.random.seed(RANDOM_SEED)

def generate_data(n=500):
    """Generate synthetic experimental data."""
    x = np.random.randn(n)
    y = 0.6 * x + np.random.randn(n) * 0.5
    return pd.DataFrame({"x": x, "y": y})

def run_analysis(df):
    """Run statistical analysis."""
    r, p = stats.pearsonr(df["x"], df["y"])
    n = len(df)
    d = 2 * r / np.sqrt(1 - r**2)
    ci_low = r - 1.96 * np.sqrt((1 - r**2) / (n - 2))
    ci_high = r + 1.96 * np.sqrt((1 - r**2) / (n - 2))
    
    print(f"Sample Size (n): {n}")
    print(f"Pearson r: {r:.4f}")
    print(f"Cohen's d: {d:.4f}")
    print(f"95% CI: [{ci_low:.4f}, {ci_high:.4f}]")
    print(f"p-value: {p:.6f}")
    return {"r": r, "p": p, "d": d, "ci": (ci_low, ci_high), "n": n}

def plot_results(df, results):
    """Create visualization."""
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    axes[0].scatter(df["x"], df["y"], alpha=0.4, s=15, c="teal")
    z = np.polyfit(df["x"], df["y"], 1)
    poly = np.poly1d(z)
    xs = np.linspace(df["x"].min(), df["x"].max(), 100)
    axes[0].plot(xs, poly(xs), "r-", linewidth=2)
    axes[0].set_xlabel("Independent Variable")
    axes[0].set_ylabel("Dependent Variable")
    axes[0].set_title(f"r={results['r']:.3f}, p={results['p']:.4f}")
    
    sns.histplot(df["y"], kde=True, ax=axes[1], color="teal")
    axes[1].set_title("Distribution of DV")
    
    plt.tight_layout()
    plt.savefig("figures/results.png", dpi=150, bbox_inches="tight")
    print("Saved figures/results.png")

if __name__ == "__main__":
    import os
    os.makedirs("figures", exist_ok=True)
    df = generate_data()
    df.to_csv("data/synthetic_data.csv", index=False)
    results = run_analysis(df)
    plot_results(df, results)
    print("\\nDone! Check figures/ for plots.")
`);

      zip.folder("data");
      zip.file("data/.gitkeep", "");
      zip.folder("figures");
      zip.file("figures/.gitkeep", "");

      // Run scripts
      zip.file("run.sh", "#!/bin/bash\nset -e\npython -m venv .venv\nsource .venv/bin/activate\npip install -r requirements.txt\nmkdir -p data figures\npython main.py\necho 'Done! Results in figures/'\n");
      zip.file("run.bat", "@echo off\npython -m venv .venv\n.venv\\Scripts\\activate\npip install -r requirements.txt\nmkdir data 2>nul\nmkdir figures 2>nul\npython main.py\necho Done! Results in figures\\\n");

      // Paper JSON
      zip.file("paper.json", JSON.stringify(paper, null, 2));

      const blob = await zip.generateAsync({ type: "blob" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `aion-reproducibility-package.zip`;
      a.click();
      URL.revokeObjectURL(url);

      setExported(true);
      setTimeout(() => setExported(false), 4000);
    } catch (e) {
      console.error("Export error:", e);
    } finally {
      setExporting(false);
    }
  };

  return (
    <button
      onClick={exportPackage}
      disabled={exporting || !paper}
      className="aion-glow-button text-xs px-4 py-2 flex items-center gap-1.5 !rounded-xl !shadow-sm hover:!shadow-md disabled:opacity-50"
    >
      {exporting ? (
        <Loader2 className="h-3.5 w-3.5 animate-spin" />
      ) : exported ? (
        <CheckCircle2 className="h-3.5 w-3.5" />
      ) : (
        <Archive className="h-3.5 w-3.5" />
      )}
      {exporting ? "Packaging…" : exported ? "Exported!" : "Reproducibility"}
    </button>
  );
}
